# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Bikuuuu.TinyTracker
PackageVersion: 1.0.4
InstallerLocale: en-US
MinimumOSVersion: 10.0.22621.0
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ElevationRequirement: elevatesSelf
ProductCode: TinyTracker_is1
ReleaseDate: 2026-10-01
AppsAndFeaturesEntries:
- DisplayName: Tiny Tracker
  Publisher: Bikuuuu
  ProductCode: TinyTracker_is1
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Bikuuuu/tiny-tracker/releases/download/v1.0.4/TinyTracker-Setup-1.0.4-x64.exe
  InstallerSha256: A64DF8F31042B865086020C819E008FD3FBAA2CA17220A9807EE50E5561E6909
ManifestType: installer
ManifestVersion: 1.12.0
